## linear algebra and probability

In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("winequality-red.csv", sep=";")

In [5]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

1.Load the dataset and handle missing values

In [6]:
df.shape

(1599, 12)

In [8]:
df = df.fillna(df.mean(numeric_only=True))

In [9]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

2.Extract alcohol and citric acid as vectors

In [11]:
alcohol = df["alcohol"].values
citric_acid = df["citric acid"].values

In [12]:
# Check vector size
print("Alcohol:", alcohol.shape)
print("Citric Acid:", citric_acid.shape)

Alcohol: (1599,)
Citric Acid: (1599,)

In [13]:
# Show first 10 values
print(alcohol[:10])
print(citric_acid[:10])

[ 9.4  9.8  9.8  9.8  9.4  9.4  9.4 10.   9.5 10.5]
[0.   0.   0.04 0.56 0.   0.   0.06 0.   0.02 0.36]

3.Calculate covariance matrix

In [14]:
alcohol = df["alcohol"].values
density = df["density"].values

In [15]:
cov_matrix = np.cov((alcohol, density), rowvar=False)

In [16]:
print(cov_matrix)

[[35.29848242 36.98312352 36.9822833  ... 42.02889669 38.66915098
  42.02994696]
 [36.98312352 38.74816512 38.7472848  ... 44.03475082 40.51465925
  44.03585122]
 [36.9822833  38.7472848  38.7464045  ... 44.03375039 40.5137388
  44.03485077]
 ...
 [42.02889669 44.03475082 44.03375039 ... 50.04260907 46.04225565
  50.04385961]
 [38.66915098 40.51465925 40.5137388  ... 46.04225565 42.36168626
  46.04340622]
 [42.02994696 44.03585122 44.03485077 ... 50.04385961 46.04340622
  50.04511017]]

4.Eigenvalues and eigenvectors

In [30]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Sort from largest to smallest
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:,idx]

In [29]:
# Get top 2 eigenvalues
print("Top 2 Eigenvalues:")
print(eigenvalues[:2])

# Get their eigenvectors
print("\nCorresponding Eigenvectors:")
print(eigenvectors[:,:2])

Top 2 Eigenvalues:
[1.13564827e+00 2.68507580e-06]

Corresponding Eigenvectors:
[[ 9.99999614e-01  8.78753184e-04]
 [-8.78753184e-04  9.99999614e-01]]

5.Find the most common wine quality

In [33]:
# Count quality scores
quality_counts = df["quality"].value_counts()

# Find most common quality
most_common = df["quality"].mode()[0]

print("Quality counts:",quality_counts)
print("\nMost common quality:", most_common)

Quality counts: quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

Most common quality: 5

In [34]:
# Count wines with most common quality
count = quality_counts[most_common]
total = len(df)

# Calculate probability
probability = count / total

print("Count:", count)
print("Probability:", probability)
print("Percentage:", probability * 100)

Count: 681
Probability: 0.425891181988743
Percentage: 42.589118198874296