## Regression Assignment

### California Housing Dataset

In [28]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

### 1. Loading the Dataset

In [29]:
housing = fetch_california_housing()

df = pd.DataFrame(housing.data, columns=housing.feature_names)
df["Target"] = housing.target

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [30]:
df.shape

(20640, 9)

In [31]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Target        0
dtype: int64

In [32]:
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

### 2. Data Preprocessing

The target variable is separated from the input features.
Missing values were checked. Feature scaling is performed
because Linear Regression and SVR can benefit from standardized
features.

In [33]:
X = df.drop("Target", axis=1)
y = df["Target"]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)                                                     #split the data

In [35]:
scaler = StandardScaler()

In [36]:
X_train_scaled = scaler.fit_transform(X_train)  #scale training data

In [37]:
X_test_scaled = scaler.transform(X_test)   #scale test data

## 1. Linear Regression

How it works: It finds a straight-line relationship between the features and house prices to make predictions.
Why suitable: It is simple and useful for predicting the continuous house prices in this dataset.

## 2. Decision Tree Regressor

How it works: It uses a series of questions or conditions about the features to predict the house price.
Why suitable: It can handle non-linear relationships between housing features and prices.

## 3. Random Forest Regressor

How it works: It creates many decision trees and combines their predictions to get the final result.
Why suitable: It gives more reliable predictions and can handle complex relationships in the dataset.

## 4. Gradient Boosting Regressor

How it works: It builds trees one after another, with each new tree trying to correct the errors of the previous tree.
Why suitable: It can capture complex patterns and often performs well on housing data.

## 5. Support Vector Regressor (SVR)

How it works: It finds the best function for predicting values while keeping errors within an acceptable range.
Why suitable: It can handle non-linear relationships, but feature scaling is important for SVR.

##Linear Regression model

In [38]:
linear_model = LinearRegression()
linear_model.fit(X_train_scaled, y_train)
linear_pred = linear_model.predict(X_test_scaled)

In [39]:
linear_pred[:10]

array([0.71912284, 1.76401657, 2.70965883, 2.83892593, 2.60465725,
       2.01175367, 2.64550005, 2.16875532, 2.74074644, 3.91561473])

In [40]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": linear_pred
})

comparison.head(10)

    Actual  Predicted
0  0.47700   0.719123
1  0.45800   1.764017
2  5.00001   2.709659
3  2.18600   2.838926
4  2.78000   2.604657
5  1.58700   2.011754
6  1.98200   2.645500
7  1.57500   2.168755
8  3.40000   2.740746
9  4.46600   3.915615

MSE = Mean Squared Error

In [41]:
mse = mean_squared_error(y_test, linear_pred)

MAE = Mean Absolute Error

In [42]:
mae = mean_absolute_error(y_test, linear_pred)

R²

In [43]:
r2 = r2_score(y_test, linear_pred)

In [44]:
print("MSE:", mse)
print("MAE:", mae)
print("R² Score:", r2)

MSE: 0.5558915986952442
MAE: 0.5332001304956565
R² Score: 0.575787706032451

## Other 4 models

In [45]:
models = {
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(
        n_estimators=100,
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingRegressor(
        random_state=42
    ),
    "SVR": SVR()
}

Train the remaining models

In [46]:
results = [
    ["Linear Regression", mse, mae, r2]
]

for name, model in models.items():

    if name == "SVR":
        model.fit(X_train_scaled, y_train)
        prediction = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        prediction = model.predict(X_test)

    mse = mean_squared_error(y_test, prediction)
    mae = mean_absolute_error(y_test, prediction)
    r2 = r2_score(y_test, prediction)

    results.append([name, mse, mae, r2])

In [47]:
results_df = pd.DataFrame(
    results,
    columns=["Model", "MSE", "MAE", "R2 Score"]
)

results_df

               Model       MSE       MAE  R2 Score
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.495235  0.454679  0.622076
2      Random Forest  0.255368  0.327543  0.805123
3  Gradient Boosting  0.293997  0.371643  0.775645
4                SVR  0.357004  0.398599  0.727563

## Find the best model

In [48]:
best_model = results_df.loc[
    results_df["R2 Score"].idxmax()
]

print(best_model)

Model       Random Forest
MSE              0.255368
MAE              0.327543
R2 Score         0.805123
Name: 2, dtype: object

## Find the worst model

In [49]:
worst_model = results_df.loc[
    results_df["R2 Score"].idxmin()
]

print(worst_model)

Model       Linear Regression
MSE                  0.555892
MAE                    0.5332
R2 Score             0.575788
Name: 0, dtype: object

## Conclusion

In this assignment, five regression algorithms were applied
to the California Housing dataset.

The models used were Linear Regression, Decision Tree,
Random Forest, Gradient Boosting and Support Vector Regression.

The models were evaluated using MSE, MAE and R² Score.
Lower MSE and MAE indicate better performance, while a higher
R² Score indicates better performance.

Based on the results, the model with the highest R² Score
was considered the best-performing model.

### Result

The best-performing model was Random Forest.

The worst-performing model was Linear Regression.